# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 706e9a9c108c8133388017ff1ebce5a0a7088e74ac850250d4c87065d97da30f18ed7919c0a63e3e34787074ebc02c86d78ce04e515614e8d23bf797d00baad5

test:
  secret_key_base: 3ffb401d44b4346835dbe6b7f2178a1bfbc6f42b47a960475a7a3e3b15afb47b96e7b02da6d321e426396394d22159edf26cd1f28ec43e05521f4c19eb05cc06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
